# Generated by Django 3.2.9 on 2021-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='posts/photos'),
        ),
    ]
