# Generated by Django 3.2.9 on 2021-12-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('blogs', '0003_alter_post_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
