# Generated by Django 3.2.9 on 2021-12-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='fix-me', unique=True),
            preserve_default=False,
        ),
    ]
